# Generated by Django 6.1 on 2026-09-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.CharField(max_length=270, unique=True)),
                ('excerpt', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=150, null=True)),
                ('author_avatar', models.ImageField(blank=True, null=True, upload_to='authors/')),
                ('published_date', models.DateField(blank=True, null=True)),
                ('published_date_jalali', models.CharField(blank=True, max_length=20, null=True)),
                ('duration', models.IntegerField(default=5)),
                ('views', models.BigIntegerField(default=0)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('featured', models.CharField(choices=[('popular', 'Popular'), ('featured', 'Featured'), ('new', 'New'), ('normal', 'Normal')], default='normal', max_length=20)),
                ('date_range', models.CharField(blank=True, choices=[('month', 'This Month'), ('three-months', 'Last 3 Months'), ('six-months', 'Last 6 Months'), ('year', 'Last Year')], max_length=30, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
        migrations.CreateModel(
            name='ArticleBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('heading', 'Heading'), ('paragraph', 'Paragraph'), ('image', 'Image'), ('quote', 'Quote'), ('lead', 'Lead')], max_length=20)),
                ('block_order', models.IntegerField()),
                ('text', models.TextField(blank=True, null=True)),
                ('src', models.CharField(blank=True, max_length=255, null=True)),
                ('alt', models.CharField(blank=True, max_length=255, null=True)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('block_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'بلوک محتوا',
                'verbose_name_plural': 'بلوک\u200cهای محتوا',
                'ordering': ['block_order'],
            },
        ),
        migrations.CreateModel(
            name='ArticleRelated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'مقاله مرتبط',
                'verbose_name_plural': 'مقالات مرتبط',
            },
        ),
    ]
