# Generated by Django 6.1 on 2026-09-24 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='places.category'),
        ),
        migrations.AddField(
            model_name='articleblock',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='articles.article'),
        ),
        migrations.AddField(
            model_name='articlerelated',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_from', to='articles.article'),
        ),
        migrations.AddField(
            model_name='articlerelated',
            name='related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to', to='articles.article'),
        ),
        migrations.AddField(
            model_name='article',
            name='related_articles',
            field=models.ManyToManyField(blank=True, through='articles.ArticleRelated', to='articles.article'),
        ),
        migrations.AlterUniqueTogether(
            name='articleblock',
            unique_together={('article', 'block_order')},
        ),
        migrations.AlterUniqueTogether(
            name='articlerelated',
            unique_together={('article', 'related')},
        ),
    ]
