# Generated by Django 6.1 on 2026-09-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='visit_count',
        ),
        migrations.AddField(
            model_name='place',
            name='contact_info',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
