# Generated by Django 6.1 on 2026-09-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_place_visit_count_place_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='visit_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
