# Generated by Django 6.1 on 2026-09-13 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_place_visit_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planattraction',
            options={'ordering': ['day_number', 'visit_order']},
        ),
        migrations.AddField(
            model_name='plan',
            name='budget_toman',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='companions',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='plan',
            name='duration_days',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_children',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='interests',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='trip',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL),
        ),
    ]
