# Generated by Django 6.1 on 2026-09-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='daily_durations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
