# Generated by Django 6.1 on 2026-09-24 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.CharField(choices=[('1_day', '1 Day'), ('2_days', '2 Days'), ('3_days', '3 Days'), ('5_days', '5 Days'), ('7_days', '7 Days')], max_length=20)),
                ('duration_days', models.IntegerField(default=1)),
                ('badge', models.CharField(blank=True, max_length=50, null=True)),
                ('estimated_cost', models.BigIntegerField(default=0)),
                ('budget_toman', models.BigIntegerField(default=0)),
                ('companions', models.IntegerField(default=2)),
                ('has_children', models.BooleanField(default=False)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='plans/')),
                ('color', models.CharField(default='#118b71', max_length=20)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'پلن',
                'verbose_name_plural': 'پلن\u200cها',
            },
        ),
        migrations.CreateModel(
            name='PlanAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(default=1)),
                ('visit_order', models.IntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.plan')),
            ],
            options={
                'verbose_name': 'جاذبه پلن',
                'verbose_name_plural': 'جاذبه\u200cهای پلن',
                'ordering': ['day_number', 'visit_order'],
                'unique_together': {('plan', 'place')},
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='attractions',
            field=models.ManyToManyField(related_name='plans', through='planner.PlanAttraction', to='places.place'),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=220, unique=True)),
                ('route_type', models.CharField(choices=[('walk', 'Walking'), ('car', 'Car'), ('bike', 'Bike')], default='walk', max_length=10)),
                ('duration_minutes', models.IntegerField(default=20)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_scenic', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('historical_significance', models.TextField(blank=True, null=True)),
                ('access_info', models.TextField(blank=True, null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='routes/')),
                ('rating_avg', models.FloatField(default=0)),
                ('visit_count', models.BigIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.category')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes_as_destination', to='places.place')),
                ('origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes_as_origin', to='places.place')),
            ],
            options={
                'verbose_name': 'مسیر',
                'verbose_name_plural': 'مسیرها',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration_days', models.IntegerField()),
                ('companions', models.IntegerField(default=1)),
                ('has_children', models.BooleanField(default=False)),
                ('budget_toman', models.BigIntegerField()),
                ('interests', models.JSONField(blank=True, default=list)),
                ('suggested_places', models.JSONField(blank=True, default=list)),
                ('daily_durations', models.JSONField(blank=True, default=list)),
                ('suggested_routes', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سفر',
                'verbose_name_plural': 'سفرها',
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_name', models.CharField(max_length=150)),
                ('stop_order', models.IntegerField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.place')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='planner.route')),
            ],
            options={
                'verbose_name': 'ایستگاه',
                'verbose_name_plural': 'ایستگاه\u200cها',
                'unique_together': {('route', 'stop_order')},
            },
        ),
    ]
